### ISSUE TITLE
Plugin constantly in deferred mode

### ISSUE THREAD

**Issue by cesm1980** [PredatorCZ/HavokMax#5]
(Version 1.6) - Not sure if this only happens on max 2012 but the plugin is only actually loaded the first time it's used, afterwards, even if i close max without making it crash, the plugin stays permanently in deferred mode and i have to manually load it everytime i start max on the plugin manager, the only way to temporarly fix this is close max, delete the plugin, start max, then close it again, put the plugin in there again and if i start max it will sucessfully autoload just the first time it's used. This doesn't happen to you? 

And by the way, of course, if i try loading a file with the plugin in deferred mode without loading it manually, immediatly makes max crash as usual.

**Comment by PredatorCZ** [comment]
Yes, you cannot use plugin in defered mode.
For me, this seems like older versions are handling such plugins differently.

**Comment by cesm1980** [comment]
Ok, i just tried version 1.8 and even tough the plugin continues to be in deferred mode NOW it can be used! Because i noticed that by checking the plugin manager AFTER i loaded a hkx file, now it shows "loaded", apparently importing the file did auto-load it, but this wasn't possible in version 1.6 so apparently that dialog fix you did, fixed this as well.

By the way, the other plugin i use for skyrim, nifloader, also had the same behavior, always starts in deferred mode and auto-loads when we import a file using the plugin so yeah it's normal to be like this at least in max 2012, so yeah, this issue is fixed.

**Comment by PredatorCZ** [comment]
I just updated V1.8, deferred bug should be completely eliminated. 
Since I tested it a little and bug you described still occurred (crash after max restart).

**Comment by cesm1980** [comment]
What?? Strange... i tested more than once, and at least on max 2012 it does not crash, but note it does the same with other plugins i use like nifloader, smdimporter, etc, they all start in deferred mode too and then auto-load by max when we import a file, only now i discovered that max does this, but i am not sure if it's like this on your version of max.

You say that it still crashes after max restart? You mean that you have to manually load it in the plugin manager every time you restart max then, to be able to use the plugin without crash? Not sure it might be related to the version you use, with me it always crashed with version 1.6 in deferred mode, and now it doesn't anymore, not sure what the say then, if it does crash with your version then yeah you should try fixing it then, for other persons that use the other versions, i wonder why 1.6 crashed in deferred mode and 1.8 doesn't, strange...

UPDATE : only now i realized what you said when you mentioned updating version 1.8 so i just downloaded the updated version, unfortunately i see no difference, the first time after putting on the folder, yeah it autoloads and appears as loaded, but after closing and restarting max it still appears as deferred, but auto-loading after opening a file, still no crash yet. It shows loaded on your version now everytime you start max? If so then it's normal like this on max 2012 then...

**Comment by PredatorCZ** [comment]
Tested on 2012. I had re-released V1.8.
And yes, most of will plugins start in deferred mode, to save memory and stuff.
3DS Max will load/unload them as it wishes. So you don't need to worry about that.

Regardless, if everything is okay, you can close this issue.
